# handlers file for apache_install_yum
- name: "apache restart"
  service:
   name: "httpd"
   state: "restarted"
   enabled: yes
  register: apache_restart
- debug: msg=apache_restart
- name: "restart firewall"
  service:
   name: "firewalld"
   state: 'restarted'
