# tasks file for apache_install_yum
- name: "apache install"
  yum:
   name: "httpd"
   state: "present"
- name: "start apache"
  service:
   name: "httpd"
   state: "started"
   enabled: "yes"
- name: "open port 80 input"
  iptables:
   chain: INPUT
- name: "open port 80 output"
  iptables:
   chain: OUTPUT
   protocol: tcp
   destination_port: 80
- name: "install php"
  yum:
   name: "php,php-mysql,php-xml,php-mbstring,php-mcrypt,php-gd,php-intl"
   state: "present"
#  when: php_install|default(False)|bool
  notify: ["apache restart"]
