# tasks file for server_init
- name: "update system"
  yum:
   name: '*'
   state: "latest"

- name: "create user"
  user:
   name: "{{user_name}}"
   append: yes
   groups: "wheel"

- name: "change ansible passwd"
  shell: echo "{{user_name}}:{{user_passwd}}" | chpasswd

- name: "no passwd ask for sudo cmd"
  lineinfile:
   path: "/etc/sudoers"
   state: "present"
   line: "{{user_name}} ALL=(ALL:ALL) NOPASSWD: ALL"

- name: "change root pass"
  shell: echo "root:{{root_passwd}}" | chpasswd
