# tasks file for apache_install
- name: "apache instalation"
  apt:
   name: "apache2"
   state: "present"
- name: "php install"
  apt:
   name: "php"
   state: "present"
- name: "apache activation"
  service:
   name: "apache2"
   state: "started"
   enabled: yes
- name: "open port 80 for http protocol"
  iptables:
   chain: INPUT
   protocol: tcp
   destination_port: 80
