# tasks file for ansible_user
- name: "create ansible user"
  user:
   name: "{{ansible_username}}"
#   shell: "/bin/bash"
   # ajouté l'utilisateur a wheel
   append: yes
   groups: "wheel"

- name: "change the ansible user passwd"
  shell: echo "{{ansible_username}}:{{ansible_passwd}}" | chpasswd
